<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //1. async (异步) 函数
        //1) 函数的返回值为Promise对象
        //2) promise对象的结果由 async 函数执行的返回值决定

        //2. await 表达式
        //1) await 右侧表达式一般为Promise对象，但也可以是其他的值
        //2) 如果表达式是 promise 对象，await 返回的是 Promise 成功的值
        //3) 如果表达式是其他的值，直接将此值作为await的返回值

        //3. 注意：
        //await 必须写在 async 函数中，但 async 函数中可以没有 await 
        //如果 await 的表达式是 Promise 失败了 ，就会抛出异常，需要通过 try ... catch 来捕获处理


        // async function fn1() { //async函数
        //      return 1
        // return Promise.resolve(1)
        //  }
        //  const result = fn1()
        //  console.log(result) // async函数返回的值是一个 promise 对象 并且是一个成功的 Promise


        //上面是成功的Promise 那失败的promise 呢 有两种 抛出异常和 失败的Promise
        //  async function fn2(){
        //     // throw 2 
        //    return Promise.reject(3)
        //  }
        //  const result2 = fn2()
        // //  console.log(result2) 在这里打印已经没意义了 下面来用then

        // result2.then(
        //     value => {
        //         console.log('onResolved',value)
        //     },
        //     reason => {
        //         console.log('onRejected',reason)
        //     }
        // )


        //返回一个延迟成功或者延迟失败的 Promise
        // async function fn3() {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             resolve(4)
        //         }, 1000)
        //     })
        // }
        // const result3 = fn3();
        // result3.then(
        //     value => {
        //         console.log('onResolved', value)
        //     },
        //     reason => {
        //         console.log('onRejected', reason)
        //     }
        // )


        // await 表达式
        //     function fn4() {
        //         return new Promise((resolve,reject) => {
        //             setTimeout(() => {
        //                 resolve(5)
        //             },1000)
        //         })
        //     }
        //     console.log(fn4());
        //    async function fn5() { //注意：必须在函数左边加 async
        //         const value =await fn4() //字面意思 等待fn4() 执行的结果值 可以直接获取传入的成功的数据 省去了then() (是不是编程更简单了)
        //         console.log('value',value) 
        //     }
        //     fn5();


        //     async function fn6() { //注意：必须在函数左边加 async
        //         const value =await 2+2 //如果await 右侧不是 Promise 呢？ 获取的直接就是这个表达式的结果
        //         console.log('value',value) 
        //     }
        //     fn6();


        //如果 promise 的结果是失败呢 
        // function fn7() {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             reject(6)
        //         }, 1000)
        //     })
        // }
        // async function fn8() {
        //     try {
        //         const value = await fn7() //这里是成功的值
        //         console.log('value', value)
        //     } catch(error){
        //         console.log('reason 失败的结果是', error)//直接打印失败的值
        //     }
        // }
        // fn8();

        // 到这一步基本对promise基本就略知一二了  拜~
    </script>
</body>

</html>